language: rust
rust:
 - stable
 - beta
 - nightly
install:
 - rustup component add clippy
 - rustup component add rustfmt-preview
matrix:
 allow_failures:
  - rust: nightly
script:
 - cargo fmt -- --check
 - cargo clippy -- -D warnings
 - cargo test

cache: cargo
