[package]
name = "zoom-lomax"
version = "0.1.0"
authors = ["John Levon <levon@movementarian.org>"]
edition = "2018"

[profile.dev]
panic = "abort"

[dependencies]
chrono = "0.4"
chrono-tz = "0.4"
dirs = "1.0.0"
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
